# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: marketplace_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: taco
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - marketplace_network
    # Опционально: настройки для продакшена
    command: --wiredTigerCacheSizeGB 1.5

  # Опционально: MongoDB Express (веб-интерфейс для управления)
  mongo-express:
    image: mongo-express
    container_name: marketplace_mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - marketplace_network

volumes:
  mongodb_data:

networks:
  marketplace_network:
    driver: bridge


