spring:
    application:
        name: "taco-cloud"
    thymeleaf:
        cache: false
    datasource:
        url: jdbc:postgresql://127.0.0.1:5433/taco
        username: "postgres"
        password: "postgres"
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            mode: always
            schema-locations: "classpath:schema.sql"

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:9000/oauth2/jwks
  # security:
    #     oauth2:
      #       client:
            #    registration:
          #    #       <oauth2 or openid provider name>:
  #                      clientId: <client id>
   #                     clientSecret: <client secret>
    #                    scope: <comma-separated list of requested scopes>
taco:
    orders:
       pageSize: 10

