spring:
    application:
        name: "taco-cloud"
    thymeleaf:
        cache: false
    data:
        mongodb:
            host: mongodb.tacocloud.com
            port: 27017
            username: tacocloud
            password: s3cr3tp455w0rd
            database: tacoclouddb
